package com.example.speakup.Objects;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

/**
 * Represents a user's recording in the SpeakUp application.
 * <p>
 * This class stores information about a practice recording, including the user who made it,
 * the question answered, the date of recording, the score achieved, and any AI-generated feedback.
 * It is used for storing and retrieving recording data from Firebase Realtime Database.
 * </p>
 */
public class Recording implements Serializable {
    /**
     * The unique identifier of the user who created the recording.
     */
    private String userId;

    /**
     * The unique identifier for the recording itself.
     */
    private String recordingId;

    /**
     * The identifier of the question that was answered in this recording.
     */
    private String questionId;

    /**
     * The title or name to be displayed for this recording (e.g., topic name).
     */
    private String displayTitle;

    /**
     * The date and time when the recording was created.
     */
    private Date dateRecorded;

    /**
     * The score assigned to the recording (e.g., based on analysis).
     */
    private int score;

    /**
     * A map containing feedback generated by AI, where keys are categories and values are the feedback text.
     */
    private Map<String, TopicDetail> aiFeedBack;

    /**
     * Constructs a new Recording with the specified details.
     *
     * @param userId       The unique identifier of the user.
     * @param questionId   The identifier of the question being answered.
     * @param displayTitle The display title for the recording.
     * @param dateRecorded The date and time the recording was made.
     * @param score        The score achieved.
     * @param aiFeedBack   The AI feedback map.
     */
    public Recording(String userId, String questionId, String displayTitle, Date dateRecorded, int score, Map<String, TopicDetail> aiFeedBack) {
        this.userId = userId;
        this.questionId = questionId;
        this.displayTitle = displayTitle;
        this.dateRecorded = dateRecorded;
        this.score = score;
        this.aiFeedBack = aiFeedBack;
    }

    /**
     * Gets the user ID associated with this recording.
     *
     * @return The user ID.
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Gets the unique identifier of the recording.
     *
     * @return The recording ID.
     */
    public String getRecordingId() {
        return recordingId;
    }

    /**
     * Sets the unique identifier of the recording.
     *
     * @param recordingId The new recording ID.
     */
    public void setRecordingId(String recordingId) {
        this.recordingId = recordingId;
    }

    /**
     * Gets the question ID associated with this recording.
     *
     * @return The question ID.
     */
    public String getQuestionId() {
        return questionId;
    }

    /**
     * Gets the display title of the recording.
     *
     * @return The display title.
     */
    public String getDisplayTitle() {
        return displayTitle;
    }

    /**
     * Gets the date and time when the recording was made.
     *
     * @return The date recorded.
     */
    public Date getDateRecorded() {
        return dateRecorded;
    }

    /**
     * Gets the score assigned to the recording.
     *
     * @return The score.
     */
    public int getScore() {
        return score;
    }

    /**
     * Gets the map of AI-generated feedback.
     *
     * @return A map containing feedback categories and TopicDetail(score and summary).
     */
    public Map<String, TopicDetail> getAiFeedBack() {
        return aiFeedBack;
    }

    /**
     * Default constructor required for calls to DataSnapshot.getValue(Recording.class).
     */
    public Recording() {}
}
